[tool.flake8]
per-file-ignores = [
    '__init__.py:F401', # module imported but unused
]
max-line-length = 120
count = true

[tool.black]
line-length = 120
include = '\.pyi?$'
force-exclude = '/migrations/'

[tool.isort] # only applying changes if they don't introduce syntax errors
atomic = true
skip_gitignore = true
profile = 'black'

[tool.mypy]
disallow_untyped_defs = true
disable_error_code = ['assignment', 'no-redef', 'union-attr', 'override']
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
follow_imports = 'skip'
install_types = true
exclude = [
    'manage.py',
    'config/settings.py',
    'tests/',
    'config/urls.py',
    'users/middlewares/auth_middleware.py',
    'hometask/services/bulk_create_objects.py',
]

[tool.django-stubs]
django_settings_module = "config.settings"
