# Generated by Django 4.1.2 on 2022-11-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometaskimage',
            old_name='image',
            new_name='file',
        ),
    ]
