# Generated by Django 4.1.2 on 2022-11-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователь телеграма', 'verbose_name_plural': 'Пользователи телеграма'},
        ),
    ]
