# Generated by Django 4.1.2 on 2022-11-25 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_telegramuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Суперъюзер', 'verbose_name_plural': 'Суперъюзеры'},
        ),
    ]
