# Generated by Django 4.1.2 on 2022-11-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_telegramuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
