# Generated by Django 4.1.2 on 2023-01-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_telegramuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_users',
            field=models.ManyToManyField(blank=True, to='users.telegramuser'),
        ),
    ]
