# Generated by Django 4.1.2 on 2023-01-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_telegramuser_telegram_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_users',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.telegramuser'),
        ),
    ]
