name: Python package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r backend/requirements.txt
    - name: Lint with black
      run: |
        black .
    - name: Lint with isort
      run: |
        isort .
    - name: Lint with flake8
      run: |
        flake8 . --max-line-length=120

    - name: Create env file
      run: |
        touch .env
        echo DATABASE_NAME=postgres >> .env
        echo DATABASE_USER=postgres >> .env
        echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
        echo DATABASE_HOST=postgres >> .env
        echo DATABASE_PORT=5432 >> .env
        echo POSTGRES_VERSION=12.0-alpine >> .env
        echo POSTGRES_USER=postgres >> .env
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
        echo POSTGRES_DB=postgres >> .env
        cat .env

    - name: Build docker image
      run: docker-compose up -d --build

    - name: Test with pytest
      run: docker-compose exec -T backend pytest
